describe("Coroutines", function()
	describe("coroutine.running", function()
		it("returns false if we're the not the main coroutine :lua>=5.2", function()
			local co = coroutine.create(function() return coroutine.running() end)
			local ok, running, is_main = coroutine.resume(co)
			expect(ok):eq(true)
			expect(running):eq(co)
			expect(is_main):eq(false)
		end)
	end)
end)
